// import { AnalysisResult } from '../../../apps/home/store/aiAnalysisStore';

// export class PDFGenerator {
//   static async generateAnalysisPDF(analysis: AnalysisResult, toolName: string): Promise<void> {
//     try {
//       // Create PDF content
//       const pdfContent = this.createPDFContent(analysis, toolName);
      
//       // Generate PDF using jsPDF or similar library
//       // For now, we'll simulate PDF generation
//       console.log('Generating PDF with content:', pdfContent);
      
//       // Simulate download
//       this.downloadPDF(pdfContent, `ai-analysis-${toolName}-${new Date().toISOString().split('T')[0]}.pdf`);
      
//     } catch (error) {
//       console.error('Error generating PDF:', error);
//       throw error;
//     }
//   }

//   private static createPDFContent(analysis: AnalysisResult, toolName: string): string {
//     const timestamp = new Date(analysis.timestamp).toLocaleString();
    
//     let content = `
// AI Analysis Report
// ==================

// Tool: ${toolName}
// Date: ${timestamp}
// Video File: ${analysis.videoFile?.name || 'N/A'}

// Results:
// `;

//     Object.keys(analysis.results).forEach((key: string) => {
//       const result = analysis.results[key];
//       content += `
// ${result.label}: ${result.value}
// Trend: ${result.trend === 'up' ? '↗️ يتحسن' : result.trend === 'down' ? '↘️ يتراجع' : '→ مستقر'}
// `;
//     });

//     content += `

// Generated by Sporton AI Tools
// `;

//     return content;
//   }

//   private static downloadPDF(content: string, filename: string): void {
//     // Create a blob with the content
//     const blob = new Blob([content], { type: 'application/pdf' });
    
//     // Create download link
//     const url = window.URL.createObjectURL(blob);
//     const link = document.createElement('a');
//     link.href = url;
//     link.download = filename;
    
//     // Trigger download
//     document.body.appendChild(link);
//     link.click();
    
//     // Cleanup
//     document.body.removeChild(link);
//     window.URL.revokeObjectURL(url);
//   }

//   static async generateComparisonPDF(analyses: AnalysisResult[]): Promise<void> {
//     try {
//       const content = this.createComparisonContent(analyses);
//       this.downloadPDF(content, `ai-comparison-${new Date().toISOString().split('T')[0]}.pdf`);
//     } catch (error) {
//       console.error('Error generating comparison PDF:', error);
//       throw error;
//     }
//   }

//   private static createComparisonContent(analyses: AnalysisResult[]): string {
//     let content = `
// AI Analysis Comparison Report
// ============================

// Generated: ${new Date().toLocaleString()}

// `;

//     analyses.forEach((analysis, index) => {
//       const toolName = this.getToolName(analysis.toolId);
//       const timestamp = new Date(analysis.timestamp).toLocaleString();
      
//       content += `
// Analysis ${index + 1}: ${toolName}
// Date: ${timestamp}
// Video: ${analysis.videoFile?.name || 'N/A'}

// Results:
// `;

//       Object.keys(analysis.results).forEach((key: string) => {
//         const result = analysis.results[key];
//         content += `  ${result.label}: ${result.value} (${result.trend})\n`;
//       });

//       content += '\n';
//     });

//     content += `
// End of Report
// `;

//     return content;
//   }

//   private static getToolName(toolId: string): string {
//     const toolNames: { [key: string]: string } = {
//       'speed-tracker': 'Speed Tracker',
//       'jump-height': 'Jump Height',
//       'reaction-time': 'Reaction Time'
//     };
    
//     return toolNames[toolId] || toolId;
//   }
// }
